### PR TITLE
fix: logrotate wildcard

### LINKED ISSUE #72: [BUG]: logrotate config is flawed
### Description of the bug

Looking at my `/var/log/mlc/` directory, I see horrible things :scream: 

~~~
root@kappa2:/var/log/mlc# ls -ltra | tail -5
-rw-r--r--  1 root root         0 Sep 24 08:32 ansible.log.2.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz
-rw-r--r--  1 root root         0 Sep 24 08:32 ansible.log.2.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz
-rw-r--r--  1 root root         0 Sep 24 08:32 ansible.log.2.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz
drwxr-x---  2 root root    229376 Sep 24 08:32 .
-rw-r--r--  1 root root   1000036 Sep 24 17:05 ansible.log
~~~

These are only the last 5 lines, look at the attachment to see the full mess: [ls-ltra-var-log-mlc.txt](https://github.com/user-attachments/files/17117157/ls-ltra-var-log-mlc.txt)

I think the root cause is [this line](https://github.com/projectpotos/ansible-role-potos_basics/blob/bdf251e2dcd07d80020dfce4060d64acf7e4045e/templates/etc/logrotate.d/potos-ansible-pull.j2#L2), i.e. `/var/log/mlc/*` matches ALL files including the already rotated ones. From the manpage:

~~~
Please use wildcards with caution.  If you specify  *,  logro‐
tate will rotate all files, including previously rotated ones.
A way around this is to use the olddir directive or a more ex‐
act wildcard (such as *.log).
~~~

The behaviour can be verified by executing `logrotate -d /etc/logrotate.d/mlc-ansible-pull` as root. 

Q: Do we ever expect a different logfile than `ansible.log` in `/var/log/mlc` (or `/var/log/potos` in the generic case) and if yes, is it fair to configure logrotating only for files ending in `*log`?. 

If yes, the old line
~~~
{{ potos_basics_ansible_logdir }}/* {
~~~
could simply be replaced by 
~~~
{{ potos_basics_ansible_logdir }}/*log {
~~~

And all would be good. Agree @fadnincx ?

### Steps To Reproduce

See above.

### Additional Information

See above.

### PR DESCRIPTION
**Pull request by fadnincx**
## Description

Should fix the logrotate issue described in #72

Fixes #72

## Dependencies

N/A

### CODE REVIEW

**Comment by nis65** [comment]
When doing the bug report, I tested on my local machine with `{{ potos_basics_ansible_logdir }}/*log {` and not `.../*.log` so my test would have caught files named `syslog` too and not only `sys.log` (silly example, I know).

But good for me like that :-)

**Review by nis65 — APPROVED** [review]
lgtm

**Comment by nis65** [comment]
Hi @fadnincx I tried to approve, but as I don't have write access, my "approval" seems not to count... :shrug:

**Comment by fadnincx** [comment]
> Hi @fadnincx I tried to approve, but as I don't have write access, my "approval" seems not to count... 🤷

As a regular contributor, I gave you now more permissions on this repo. Your approval now counts.

**Pull request merged**
